#Αναγνώριση Προτύπων - Μηχανική Μάθηση - Εργασία 1
## Νικόλαος Μασούρας sdi1800112

# Ερώτημα 1: Πράξεις με Διανύσματα και Πίνακες

In [7]:

import numpy as np

np.random.seed(112)

X = np.random.randint(0,5,size=(3,4))
Y = np.random.randint(0,5,size=(4,3))
a = np.random.randint(0,5,size=(4,1))
b = np.random.randint(0,5,size=(4,1))
print("random arrays")
print("X =",X)
print("Y =",Y)

print("random vectors")
print("a =",a)
print("b =",b)
c = np.transpose(a)
#1.1 inner a,b
print("inner a,b = ",int(c.dot(b)))
#1.2 calc Xa
print("Xa = ",X.dot(a))
#1.3 calc XY
print("XY = ",X.dot(Y))
#1.4 I2-norm of a
print("I2-norm of a = ",np.linalg.norm(a))

random arrays
X = [[4 3 0 2]
 [1 4 4 0]
 [4 1 2 0]]
Y = [[4 0 0]
 [3 3 4]
 [1 0 3]
 [2 1 2]]
random vectors
a = [[2]
 [2]
 [4]
 [0]]
b = [[2]
 [0]
 [0]
 [0]]
inner a,b =  4
Xa =  [[14]
 [26]
 [18]]
XY =  [[29 11 16]
 [20 12 28]
 [21  3 10]]
I2-norm of a =  4.898979485566356


##Υπολογισμός με το χέρι
$ X = \left[\begin{array}{rrrr}
       4 & 3 & 0 & 2\\
       1 & 4 & 4 & 0\\
       4 & 1 & 2 & 0\\
       \end{array}\right],
  Y = \left[\begin{array}{rrr}
      4 & 0 & 0\\
      3 & 3 & 4\\
      1 & 0 & 3\\
      2 & 1 & 2\\
      \end{array}\right],
  a = \left[\begin{array}{r}
      2 \\ 2 \\ 4 \\ 0
      \end{array}\right],
  b = \left[\begin{array}{r}
      2 \\ 0 \\ 0 \\ 0
      \end{array}\right]
$

**1.1**

$
   <a,b> = a^Tb 
        = \left[\begin{array}{rrrr}
          2 & 2 & 4 & 0
          \end{array}\right]
          \left[\begin{array}{r}
          2 \\ 0 \\ 0 \\ 0
          \end{array}\right]
        = 2*2 + 2*0 + 4*0 + 0*0 = 4\\
$


**1.2**

$
   Xa = \left[\begin{array}{rrrr}
       4 & 3 & 0 & 2\\
       1 & 4 & 4 & 0\\
       4 & 1 & 2 & 0\\
       \end{array}\right]
       \left[\begin{array}{r}
          2 \\ 2 \\ 4 \\ 0
        \end{array}\right]
      = \left[\begin{array}{r}
          4*2 + 3*2 + 0*4 + 2*0 \\
          1*2 + 4*2 + 4*4 + 0*0 \\
          4*2 + 1*2 + 2*4 + 0*0 \\
        \end{array}\right]
      =\left[\begin{array}{r}
        14 \\
        26 \\
        18 \\
        \end{array}\right]
        \\
$

**1.3**

$
   XY = \left[\begin{array}{rrrr}
       4 & 3 & 0 & 2\\
       1 & 4 & 4 & 0\\
       4 & 1 & 2 & 0\\
       \end{array}\right]
       \left[\begin{array}{rrr}
        4 & 0 & 0\\
        3 & 3 & 4\\
        1 & 0 & 3\\
        2 & 1 & 2\\
        \end{array}\right]
      = \left[\begin{array}{rrr}
        4*4 + 3*3 + 0*1 + 2*2 & 4*0 + 3*3 + 0*0 + 2*1 & 4*0 + 3*4 + 0*3 + 2*2 \\
        1*4 + 4*3 + 4*1 + 0*2 & 1*0 + 4*3 + 4*0 + 0*1 & 1*0 + 4*4 + 4*3 + 0*2 \\
        4*4 + 1*3 + 2*1 + 0*2 & 4*0 + 1*3 + 2*0 + 0*1 & 4*0 + 1*4 + 2*3 + 0*2 \\
        \end{array}\right]
      = \left[\begin{array}{rrr}
        29 & 11 & 16 \\
        20 & 12 & 28 \\
        21 & 3  & 10 \\ 
        \end{array}\right]
        \\
$


**1.4**

$ 
\lVert a \rVert_2 = \sqrt{2^2 + 2^2 + 4^2 + 0} = \sqrt{4 + 4 + 16}= \sqrt{24} 
    = 2\sqrt{6} 
$

# Ερώτημα 2: Υπολογισμός παραγώγων

## 2.1
$ f(x) = x^TAx + b^Tx,
  A = A^T dxd, b \epsilon ℝ^d,x \epsilon ℝ^d
$


$
  \frac{∂b^Tx}{∂x} = \frac{∂x^Tb}{∂x} = b 
$
  από (69) στο https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf  


 $ \frac{∂x^TAx}{∂x} = (A + A^T)x$
   από (81) στο https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf  


 Όμως αφού $A^T = A$

 $ \frac{∂x^TAx}{∂x} = 2Ax $

  Άρα τελικά
  $ ∇f(x) = 2Ax + b$



## 2.2

#Ερώτημα 3: Gradient descent

In [15]:
import matplotlib.pyplot as plt

def f1(x1,x2):
  return ((x1 - 2)**2 + (x2 - 3)**2)
def partialf1x1(x1,x2):
  return (2*x1 - 4)

def partialf1x2(x1,x2):
  return (2*x2 - 6)

def f2(x1,x2):
  return ((1- (x2 - 3))**2 + 20*((x1 + 3) - (x2 - 3)**2)**2)

def partialf2x1(x1,x2):
  return (40*(x1 + 3 - (x2 - 3)**2))

def partialf2x2(x1,x2):
  return (-2*(4-x2) + 40*(x1 + 3 -(x2-3)**2)*(-2*x2 + 6))


def gradient_descent(curx1,curx2,rate,maxIter,function,partialx1,partialx2,funName):
  actIters = []
  precision = 0.0001
  result = []
  iters = list(range(1,maxIter+1))
  print(funName, ": G-D for starting values (%d,%d) learning rate = %.4f and max iterations = %d"%(curx1,curx2,rate,maxIter))
  for iter in range(maxIter):
    actIters.append(iter)
    prevx1 = curx1
    prevx2 = curx2
    curx1 = curx1 - (rate * partialx1(curx1,curx2))
    curx2 = curx2 - (rate * partialx2(curx1,curx2))
    fResult = function(curx1,curx2)
    result.append(fResult)
    diff1=abs(curx1-prevx1)
    diff2=abs(curx2-prevx2)
    print("Iteration",iter+1,":",funName,"(x1,x2) =",fResult)
    if (diff1 <= precision and diff2 <= precision):
      print("The local minimum occurs at (%f,%f) after %d iterations"%(curx1,curx2,iter+1))
      break

  #create plot
  plt.title("rate = %.3f maxIters = %d"%(rate,maxIter))
  plt.xlabel("iterations")
  plt.ylabel("f1(x1,x2)")
  plt.plot(actIters,result)
  plt.show()  
  

In [ ]:
gradient_descent(0,0,0.5,10,f1,partialf1x1,partialf1x2,"f1")


In [ ]:
gradient_descent(0,0,0.01,400,f1,partialf1x1,partialf1x2,"f1")


In [ ]:
gradient_descent(0,0,0.1,50,f1,partialf1x1,partialf1x2,"f1")


In [ ]:
gradient_descent(0,0,0.4,20,f1,partialf1x1,partialf1x2,"f1")


In [ ]:
gradient_descent(0,0,0.6,20,f1,partialf1x1,partialf1x2,"f1")


In [ ]:
gradient_descent(0,0,0.7,20,f1,partialf1x1,partialf1x2,"f1")


In [ ]:
gradient_descent(0,0,0.9,100,f1,partialf1x1,partialf1x2,"f1")


In [ ]:
gradient_descent(1,1,0.5,10,f1,partialf1x1,partialf1x2,"f1")


In [ ]:
gradient_descent(1,0,0.5,10,f1,partialf1x1,partialf1x2,"f1")


In [ ]:
gradient_descent(1,1,0.4,20,f1,partialf1x1,partialf1x2,"f1")


In [ ]:
gradient_descent(10,19,0.4,20,f1,partialf1x1,partialf1x2,"f1")


**Σχόλια για την f1**

1) Για αρχικές τιμές (0,0) και learning rate 0.5 η συνάρτηση βρίσκει κατευθείαν το τοπικό ελάχιστο το οποίο είναι το 0

2) Παρατηρούμε ότι για αρχικές τιμές (0,0) και learning rate "κοντά στο" 0.5 η σύκλιση επιτυγχάνεται σε λιγότερες επαναλήψεις, ενώ καθως απομακρυνόμαστε από το 0.5 είτε μεγαλώνει το learning rate είτε μικραίνει χρειάζονται όλο και περισσότερες επαναλήψεις.
Συγκεκριμένα:

 Για learning rate 0.01 318 επαναλήψεις.

 Για learning rate0.1 40 επαναλήψεις.

 Για learning rate 0.4 8 επαναλήψεις.

 Για learning rate 0.6 8 επαναλήψεις.

 Για learning rate 0.7 13 επαναλήψεις.
 
 Για learning rate 0.9 50 επαναλήψεις.

3) Για διαφορετικές αρχικές τιμές παρατηρούμε ότι ο αλγόριθμος έχει παρόμοια συμπεριφορά

In [ ]:
gradient_descent(0,0,0.001,6000,f2,partialf2x1,partialf2x2,"f2")


In [ ]:
gradient_descent(1,1,0.001,6000,f2,partialf2x1,partialf2x2,"f2")


In [ ]:
gradient_descent(2,2,0.001,6000,f2,partialf2x1,partialf2x2,"f2")


In [ ]:
gradient_descent(5,5,0.001,6000,f2,partialf2x1,partialf2x2,"f2")

In [ ]:
gradient_descent(9.01,9.01,0.001,6000,f2,partialf2x1,partialf2x2,"f2")

**Σχόλια για την f2**

1) Για αρχικές τιμές (0,0) και learning rate 0.5 συμβαίνει overflow

2) Για την αποφυγή του overflow πρέπει να επιλεγούν μικρές τιμές learning rate

3) Για αρχικές τιμές (0,0) και learning rate 0.01 επιτυγχάνεται σύγκλιση ακρίβειας 0.0001 σε 4937 επαναλήψεις 

4) Όσο μεγαλώνει  η τμή των αρχικών τιμών της συνάρτησης, αυξάνονται οι επαναλήψεις ποθ χρειάζονται για σύγκλιση